In [3]:
import torch

In [7]:
tensor_a = torch.tensor(
    [1,2,3]
)
tensor_b =torch.tensor(
    [
    [1,2,3],
    [4,5,6]
    ]
)

In [9]:
print(tensor_a + tensor_b)
print(tensor_a - tensor_b)
print(tensor_a * tensor_b)
print(tensor_a / tensor_b)
print(torch.mul(tensor_a, tensor_b)) # 等价于*

tensor([[2, 4, 6],
        [5, 7, 9]])
tensor([[ 0,  0,  0],
        [-3, -3, -3]])
tensor([[ 1,  4,  9],
        [ 4, 10, 18]])
tensor([[1.0000, 1.0000, 1.0000],
        [0.2500, 0.4000, 0.5000]])
tensor([[ 1,  4,  9],
        [ 4, 10, 18]])
